### ISSUE TITLE
Not able to get exact results for backtesting.

### ISSUE THREAD

**Issue by ketank1000** [ssssi/freqtrade_strs#11]
Im trying to get exact backtesting results you have over here https://github.com/ssssi/freqtrade_strs/blob/main/binance/backtest/E0V1E_backtest_2022-05-12_2022-11-29.txt 

But not able to get even close to the results you have.

Can you please provide hyper-opts prams file for backtesting ?

**Comment by ssssi** [comment]
you need download the same backtest pairs

**Comment by ketank1000** [comment]
Thanks got it !

**Comment by batcandoi27** [comment]
Tôi cũng không thể nào ra được kết quả tương tự như vậy !
 Bạn có thể chỉ giúp tôi sửa sai không ?

freqtrade backtesting --strategy E0V1E --timerange 20220512-20221129 --config config.json
freqtrade download-data --config config.json --timeframes 5m 1m --timerange 20220501-20230115
[config.txt](https://github.com/ssssi/freqtrade_strs/files/10446082/config.txt)
[result.txt](https://github.com/ssssi/freqtrade_strs/files/10446083/result.txt)
[E0V1E.txt](https://github.com/ssssi/freqtrade_strs/files/10446084/E0V1E.txt)
thanks u so much !

**Comment by ssssi** [comment]
> I can't get the same result either!
> 
> Can you just help me correct it?
> 
> freqtrade backtesting --strategy E0V1E --timerange 20220512-20221129 --config config.json freqtrade download-data --config config.json --timeframes 5m 1m --timerange 20220501-20230115 [config.txt](https://github.com/ssssi/freqtrade_strs/files/10446082/config.txt) [result.txt](https://github.com/ssssi/freqtrade_strs/files/10446083/result.txt) [E0V1E.txt](https://github.com/ssssi/freqtrade_strs/files/10446084/E0V1E.txt) thanks u so much !

You buy and sell params is the default value. you need to hyperopt them to get results similar to mine.The process of optimization is indispensable

**Comment by ketank1000** [comment]
Im still not able to combine the sell and buy hyperopt params.
Can you please provide ur params file ?

**Comment by ketank1000** [comment]
Can you please help me on getting the back test results ?

**Comment by ssssi** [comment]
> Im still not able to combine the sell and buy hyperopt params.
> 
> For hyperopt i used :
> 
> * 1000 epochs
> * same pairs as you have in config file.
> * SortinoHyperOptLossDaily for buy signal
> * SortinoHyperOptLoss for sell signal
> 
> Then I combined these to params, still im not half close to ur results.
> 
> Can you please provide ur params file ?

the backtest result is my another hyperopt result.the buy use SharpeHyperoptloss.

**Comment by ssssi** [comment]
> Can you please help me on getting the back test results ?

if you want get the similar result with me.the buy params need to use SharpeHyperoptloss
