### ISSUE TITLE
rejected entry signal issue

### ISSUE THREAD

**Issue by Nai-mul** [ssssi/freqtrade_strs#13]
bro i see that your e0v1e strategy rejected too many entry signal. it mean in future bot can go wrong situation. i think for backtest and dry run perpose you need to increase max entry order to minimum 10. this way strat receive more entry signal and its draw more drawdown. this way you understand if this strat hit multiple stoploss in bad situation then what happen. by this way if your strat draw small drawdown factor and if you get better risk reward. that mean this strat work well future.

**Comment by ssssi** [comment]
Thank you bro,sorry for reply too late. your advise correct, it is worth to try.
