### ISSUE TITLE
Error during the backtest of the strategy

### ISSUE THREAD

**Issue by owlswaper** [ssssi/freqtrade_strs#14]
Hello, thank you for your good strategies.
I want to use ClucHANix and ClucHANix_5m but I get this error.
Can someone help or tell me the reason

![Screenshot from 2023-03-15 10-11-30](https://user-images.githubusercontent.com/117394732/225228106-5929fdd9-81d0-4262-9263-cf86ba43678c.png)

**Comment by ssssi** [comment]
oh, i had not use this strategy for a long time.i will test it and debug this error to resolve it, then i will reply you.

**Comment by owlswaper** [comment]
Hello, thank you very much for paying attention to my question.
I understood the reason
The problem was that this strategy used a higher time frame to confirm the trend and I had not downloaded its data.

In addition, I would be very grateful if you put more strategies, I will really use this repository.
