### ISSUE TITLE
 invalid value encountered in scalar divide

### ISSUE THREAD

**Issue by boiydiego777** [ssssi/freqtrade_strs#16]
i get following error when backtesting on latest E0V1E

/home/ftuser/.local/lib/python3.11/site-packages/pandas_ta/overlap/linreg.py:53: RuntimeWarning: invalid value encountered in scalar divide
  return rn / rd

how to solve?

**Comment by ssssi** [comment]
> i get following error when backtesting on latest E0V1E
> 
> /home/ftuser/.local/lib/python3.11/site-packages/pandas_ta/overlap/linreg.py:53: RuntimeWarning: invalid value encountered in scalar divide return rn / rd
> 
> how to solve?
Thank you for your attention, I have seen your email, this is a pandas warning, does not affect the running of the program. So far, can you run the backtest results?

**Comment by boiydiego777** [comment]
i get these errors when backtesting , i also send you in private on discord ft.. kind regards

**Comment by ssssi** [comment]
> i get these errors when backtesting , i also send you in private on discord ft.. kind regards

oh,sorry,recently i use my another account evilzzq， you can dm me @evilzzq

**Comment by droidoz** [comment]
Maybe not the best solution, but you can temporarily disable the warning like this:

`import warnings`

`warnings.filterwarnings("ignore", category=RuntimeWarning) `
