### ISSUE TITLE
老哥有用freqtrade实盘吗？

### ISSUE THREAD

**Issue by hakunaMatata-haus** [ssssi/freqtrade_strs#17]
咋我用E0V1E 回测近半年收益才2.71%，配置文件也没啥设置的啊，可否交流交流

**Comment by ssssi** [comment]
有，不过最近不还好

**Comment by hakunaMatata-haus** [comment]
有个问题请教下，使用freqtrade backtesting命令回测后，用什么方法可以查看到具体的成交记录吗
