### ISSUE TITLE
Brute force btc

### ISSUE THREAD

**Issue by Bruce-The-Force** [ssssi/freqtrade_strs#19]
Hi Mees, how are you? A while back i think i was you had a python script for brute forcing bitcoin. extracting public adresses from random generated private keys. I see u deleted this, can you please reach out to me i am still very interested in this project,

Thank u 

Telegram: @CarteBlanche1

**Comment by ssssi** [comment]
> Hi Mees, how are you? A while back i think i was you had a python script for brute forcing bitcoin. extracting public adresses from random generated private keys. I see u deleted this, can you please reach out to me i am still very interested in this project,
> 
> Thank u
> 
> Telegram: @CarteBlanche1

i don't know what you are talking about.
