### ISSUE TITLE
(buy\sell )_btc_safe( \_1d)

### ISSUE THREAD

**Issue by bibinvargheset** [ssssi/freqtrade_strs#2]
I see the buy\sell _btc_safe parameter in your stratergy intialisation, can't see those used / implemted in the stratergy implementation ? am i not seeing something and what these values signify 

        "buy_btc_safe": -289,
        "buy_btc_safe_1d": -0.05,
     "sell_btc_safe": -389,

**Comment by ssssi** [comment]
> I see the buy\sell _btc_safe parameter in your stratergy intialisation, can't see those used / implemted in the stratergy implementation ? am i not seeing something and what these values signify
> 
> ```
>     "buy_btc_safe": -289,
>     "buy_btc_safe_1d": -0.05,
>  "sell_btc_safe": -389,
> ```

these values is not use in str because i hadremove btc protection buy condition
