### ISSUE TITLE
pairs for this whitelist selection problem

### ISSUE THREAD

**Issue by tonyyang1223** [ssssi/freqtrade_strs#21]
Hello , I hope this message finds you well. I wanted to express my sincere gratitude for the incredible work. Your efforts have provided me with a great deal of inspiration and have significantly influenced my own approach to algorithmic trading.

In particular, I was impressed by the performance of the backtests in your project, and I noticed that the pair_whitelist you used yielded exceptional results. I’m very interested in understanding how you went about selecting the pairs for this whitelist. Could you share some insights or criteria that guided your selection process?

**Comment by ssssi** [comment]
I just selected the binance of all the spot coins, and if you have an exception, it's probably one of the coins in the trust list that is delist
