### ISSUE TITLE
about trailing loss

### ISSUE THREAD

**Issue by YukunZEX** [ssssi/freqtrade_strs#22]
Hello, thank you for your great work, i appreciate it. i found that during backtest, there are many trades that achieved 10%+ profits. However, in dry run, the 0.003 trailing loss will kill the trade at around 3-5% profits and never let the trade achieved 10%. this caused a large gap between backtest and dryrun. this is a universal problem of fraqetrade, i wonder how do you deal with this problem. 
other discriptions about trailing trap https://botacademy.ddns.net/2023/07/09/backtest-traps-trailing-stoploss/

**Comment by ssssi** [comment]
> Hello, thank you for your great work, i appreciate it. i found that during backtest, there are many trades that achieved 10%+ profits. However, in dry run, the 0.003 trailing loss will kill the trade at around 3-5% profits and never let the trade achieved 10%. this caused a large gap between backtest and dryrun. this is a universal problem of fraqetrade, i wonder how do you deal with this problem. other discriptions about trailing trap https://botacademy.ddns.net/2023/07/09/backtest-traps-trailing-stoploss/

If you want to make a higher profit per transaction, for example, more than 5%, you can set the trailing stop above 5%.
