### ISSUE TITLE
strategy stoploss not equal with backtest and hyperopt

### ISSUE THREAD

**Issue by 8a2a8** [ssssi/freqtrade_strs#23]
strategy stoploss configuration:
```
    stoploss = -0.25
    trailing_stop = True
    trailing_stop_positive = 0.003
    trailing_stop_positive_offset = 0.03
    trailing_only_offset_is_reached = True
```
when i run hyperopt and backtest, stoploss change, like as follow:
```
freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.026
```
i'm curious about why stoploss is not equal with backtest and hyperopt

**Comment by ssssi** [comment]
hi,friend. i think you run hyperopt optimized stoploss.I think you should run the backtest first, look at the backtest results, and then decide which parameter to optimize.

**Comment by 8a2a8** [comment]
ok, I have found the reason. I made a basic mistake, my strategy library is duplicated

and I have another question on hyperopt, are you still using the optimization method below:
```
SortinoHyperOptLossDaily for buy signal
SortinoHyperOptLoss for sell signal
```

in other issue, i also found some other methods you proposed:
```
SharpeHyperoptloss for  buy signal
```

**Comment by Dadacticiel** [comment]
Hello !
I know it's not the subject of the issue, but i kinda have the same question :)
How do you use hyperopt ? For wich timerange ? Like every week ? For a whole year ?
And why shouldn't we optimize other sell parameters ?

**Comment by Dadacticiel** [comment]
sell_loss_cci and sell_loss_cci_profit might have lookahead ?
It doesn't look like it as lookahead bias, i have the same result in dry run as in backtest, even if i optimize sell_loss_cci and sell_loss_cci_profit

**Comment by 8a2a8** [comment]
> sell_loss_cci and sell_loss_cci_profit might have lookahead ? It doesn't look like it as lookahead bias, i have the same result in dry run as in backtest, even if i optimize sell_loss_cci and sell_loss_cci_profit

i mean this lookahead analysis test : <https://www.freqtrade.io/en/stable/lookahead-analysis/>

by the way, I can't guarantee that my approach will get you the optimization results you want.

**Comment by 8a2a8** [comment]
> > Hello ! I know it's not the subject of the issue, but i kinda have the same question :) How do you use hyperopt ? For wich timerange ? Like every week ? For a whole year ? And why shouldn't we optimize other sell parameters ?
> 
> i use for per month, and epochs 500, this is the official recommended parameter other paramters may not pass lookahead analysis

After using the above method for optimization,
the backtest results of the current month show a forward-looking bias, 
but strangely, there is no forward-looking bias in other months.
 Is this normal?

**Comment by ssssi** [comment]
> Hello ! I know it's not the subject of the issue, but i kinda have the same question :) How do you use hyperopt ? For wich timerange ? Like every week ? For a whole year ? And why shouldn't we optimize other sell parameters ?

 hyperopt requires constant attempts and corrections, and it takes many times to obtain appropriate parameters. If you don't have the time and energy to do this, you just need to optimize one parameter "buy_cti_32".This will greatly reduce your workload and the other parameters I have optimized for the instance. Of course, you can choose to optimize other parameters again.
