### ISSUE TITLE
Backtest of E0V1E.py

### ISSUE THREAD

**Issue by Ajin9n9** [ssssi/freqtrade_strs#25]
Hi... 
I'm new to freqtrade and came across your strategy via strat.ninja and would like to try it. I copied the config.json file and the E0V1E.py strategy. The config.json uses VolumePairList except that this is not supported by the backtest so should I put pairs in config.json and switch to StaticPairList mode or whatever...? 

Thanks in advance

**Comment by ssssi** [comment]
yeah,use staticpairlist mode and read freqtrade doc about backtest part

**Comment by Ajin9n9** [comment]
Ok merci beaucoup pour votre aide

**Comment by Mastaaa1987** [comment]
if you want to visualize backtests, or create every art config you need to start freqtrade in webserver mode... 
freqtrade webserver -c user_data/config.json
You can compare backtests, shows every pair & every candle or trade ...
The Access to Server @ http://127.0.0.1:8080 (or what the ip is from trade ui is ....)
Mfg

**Comment by 14790897** [comment]
you can use MarketCapPairList which can be used in backtest

```sh
 {
      "method": "MarketCapPairList",
      "number_assets": 250,
      "max_rank": 250,
      "refresh_period": 86400,
      "categories": []
    },
```

**Comment by Mastaaa1987** [comment]
Make a static pair list & into the Whitelist 
".*/USDT" ... Now you can Download Data for all pairs ...

**Comment by 14790897** [comment]
manual download

> How do you download-data for MarketCapPairList for backtesting ?

**Comment by Dadacticiel** [comment]
Thank you.

I have really good results on my backtests. But when in dry run, i don't get the same results.
I get the same trades but always with a different open rate and close rate, wich leads to negative results in the end.

I thought it was because of my configuration, so I tried using @Mastaaa1987 config and strategie shared here : https://github.com/ssssi/freqtrade_strs/issues/27#issuecomment-2481420090 
But i also got the same problem (very nice backtest and bad dry drun)
(thank you by the way for sharing :smile:)

For exemple, a trade in backtests with an open_rate at 0.003573 can be at 0.003545 in dry run.
Sometimes it's even worse, i got some days with 2% profit in backtest wich ends in -4% profit in dry !

Does anyone got the same kind of problem ?
I guess it's because of the market orders, or maybe my computer take too long to analyse the strategy ? (or maybe my internet connexion ?)
I tried using limit orders to reduce the slippage, but it also results in dry run orders with differents open and close rates from my backtests. (with sometimes unfilled orders).

**Comment by 14790897** [comment]
> Thank you.
> 
> I have really good results on my backtests. But when in dry run, i don't get the same results. I get the same trades but always with a different open rate and close rate, wich leads to negative results in the end.
> 
> I thought it was because of my configuration, so I tried using @Mastaaa1987 config and strategie shared here : [#27 (comment)](https://github.com/ssssi/freqtrade_strs/issues/27#issuecomment-2481420090) But i also got the same problem (very nice backtest and bad dry drun) (thank you by the way for sharing 😄)
> 
> For exemple, a trade in backtests with an open_rate at 0.003573 can be at 0.003545 in dry run. Sometimes it's even worse, i got some days with 2% profit in backtest wich ends in -4% profit in dry !
> 
> Does anyone got the same kind of problem ? I guess it's because of the market orders, or maybe my computer take too long to analyse the strategy ? (or maybe my internet connexion ?) I tried using limit orders to reduce the slippage, but it also results in dry run orders with differents open and close rates from my backtests. (with sometimes unfilled orders).

I also think that the strategy might not be performing as well as it appears. The specific reasons could be slippage or differences in the choice of trading pairs, but I tend to believe slippage is the main factor.

this is my dry run
```
ROI: Closed trades
∙ 50.771 USDT (0.48%) (10.05 Σ%)
∙ 50.822 USD
ROI: All trades
∙ 37.842 USDT (0.36%) (7.49 Σ%)
∙ 37.88 USD
Total Trade Count: 45
Bot started: 2024-11-15 09:43:39
First Trade opened: 4 days ago (2024-11-15 09:45:20)
Latest Trade opened: 3 hours ago (2024-11-19 07:40:18)
Win / Loss: 39 / 5
Winrate: 88.64%
Expectancy (Ratio): 1.15 (0.05)
Avg. Duration: 3:02:36
Best Performing: CLV/USDT: 16.06%
Trading volume: 22895.725 USDT
Profit factor: 1.44
Max Drawdown: 8.62% (44.766 USDT)
    from 2024-11-15 10:17:38 (14.59 USDT)
    to 2024-11-16 06:15:17 (-30.176 USDT)
```

**Comment by Mastaaa1987** [comment]
@Dadacticiel 
If you backtesting did you use the detail-timeframe 1m as me?
At the moment I am using a volume pair list and I have no idea how to use it in the backtest to create a comparable situation from backtest to real live. But I will try to make a comparison in the next few days and share it with you ...

**Comment by Dadacticiel** [comment]
I didn't use 1m detail.
Usually, what i do is that i have the strategy running in dry, i check the trades for 2024-11-21 for example. My dry run got 6 trades, -1.89% profit.
Then i run the backtest for 2024-11-21 with the same pairs to compare. My backtest says 13 trades, 3.43% profit.
Thats a huge difference, and it's like this almost every day.

Then i compare each trade from my dry run and my back test.
But my method is not very consistent as i might get different trades depending on cooldown, open trades on dry from precedent day... I often got different open date with 5 to 20 minutes differences, trailing stop from backtest different from dry, differents open and close rates... Hard to tell whats causing all these differences.


What i mostly see is that some market exits reduce the profit by a lot.
A trade on UTK/USDT in my backtest closing at 0.04221 with 2.04% profit, in dry asked to close with 1.40% profit wich is already less but ended with only 0.02% profit when market order fullfilled.

Market orders can sometimes reduce the profit by more than 1%.
I tried to make a proper comparaison to share but i struggle making something understandable and the results depends a lot on my start date and context.

Anyway, my dry run is almost always in negative every day while almost always positive in backtests.

**Comment by Mastaaa1987** [comment]
So it can't be possible that only 6 trades are started in the dry_run and 12 trades in the backtest! If you say that the open_date is 5 - 20 minutes different from the backtest, there seems to be a technical problem. Because if I run a backtest, the open_date only differs by about 30 seconds, which of course makes a few percent difference in profit. But does not lead to a different number of trades...
In my experience, when I use my Raspberry Pi 3, it is so weak that it cannot calculate 248 pairs quickly enough that it hangs over. (If it takes longer than 5 minutes to calculate everything but is supposed to calculate every 5 minutes, it can't work...)
Have you looked in your log to see if there is something like last candle xx minutes old...?
Otherwise I can't explain why this happens to you, because my live run results (at least the number of trades + open_date, close_date) are pretty much the same as those from the backtest...

**Comment by Dadacticiel** [comment]
Ok thank you for your answer. I have other starts running on my computer (NostalgiaForInfinity) wich take way more ressources. That can be the problem. And my internet connexion is not very good.
I'll try running E0V1E in dry in an AWS instance to see if it differs from the dry on my computer !

**Comment by Dadacticiel** [comment]
And i didn't answer but my market orders were executed immediatly, i'll check the logs when i'll have time but surely i had some struggle running the strat smoothly.

I'm interested in your snippet, don't hesitate to share or if you want some feedback :)

**Comment by Mastaaa1987** [comment]
Yes, I'm still working on it at the moment. But I still have to check whether high & low are calculated correctly. I think I'll send it to you immediately, since I can't test it with my real money and I can't run a dry_run in parallel with it...

**Comment by Mastaaa1987** [comment]
So I'm done, if everything works correctly, then it should push the exit order "fastk_profit_sell_2" 5 seconds before the new candle data comes in and everything is recalculated.
You can try it out and then tell me whether the slippage is better now.
Here is the updated strategy:
https://raw.githubusercontent.com/Mastaaa1987/freqtrade-strategie/refs/heads/main/user_data/strategies/E0V1E_test.py
(Caution The strategy name has changed to E0V1E_test)

**Comment by Dadacticiel** [comment]
Thank you, i'm running it in dry on my computer, i'll keep you informed :)

**Comment by Dadacticiel** [comment]
Here is the results for now :

| E0V1E mastaaa | E0V1E mastaaa test |
| --- | --- |
|> Freqtrade Mastaaa:|> Fretrade_mastaaa_test:|
|✓ Binance (dry): New Trade filled (#2)|✓ Binance (dry): New Trade filled (#1)|
|Pair: COTI/USDT|Pair: COTI/USDT|
|Enter Tag: buy_1|Enter Tag: buy_1|
|Amount: 3530|Amount: 3523|
|Direction: Long|Direction: Long|
|Open Rate: 0.1406 USDT|Open Rate: 0.14044 USDT|
|Total: 496.318 USDT / 496.814 USD|Total: 494.77 USDT / 495.265 USD|
|||
|> Freqtrade Mastaaa:|> Fretrade_mastaaa_test:|
|✳ Binance (dry): Exited COTI/USDT (#2)|✳ Binance (dry): Exited COTI/USDT (#1)|
|Profit: 2.06% (profit: 10.257 USDT / 10.267 USD)|Profit: 1.79% (profit: 8.865 USDT / 8.874 USD)|
|Enter Tag: buy_1|Enter Tag: buy_1|
|Exit Reason: fastk_profit_sell|Exit Reason: fastk_profit_sell_2|
|Direction: Long|Direction: Long|
|Amount: 3530|Amount: 3523|
|Open Rate: 0.141 USDT|Open Rate: 0.14 USDT|
|Exit Rate: 0.144 USDT|Exit Rate: 0.143 USDT|
|Duration: 1:20:02 (80.0 min)|Duration: 1:19:33 (79.5 min)|
|||
|> Freqtrade Mastaaa:|> Fretrade_mastaaa_test:|
|✓ Binance (dry): New Trade filled (#3)|✓ Binance (dry): New Trade filled (#2)|
|Pair: TIA/USDT|Pair: TIA/USDT|
|Enter Tag: buy_1|Enter Tag: buy_1|
|Amount: 85.66|Amount: 85.32|
|Direction: Long|Direction: Long|
|Open Rate: 5.856 USDT|Open Rate: 5.853 USDT|
|Total: 501.625 USDT / 502.127 USD|Total: 499.378 USDT / 499.877 USD|
|||
|> Freqtrade Mastaaa:|> Fretrade_mastaaa_test:|
|✳ Binance (dry): Exited TIA/USDT (#3)|✳ Binance (dry): Exited TIA/USDT (#2)|
|Profit: 0.58% (profit: 2.933 USDT / 2.936 USD)|Profit: 0.65% (profit: 3.263 USDT / 3.266 USD)|
|Enter Tag: buy_1|Enter Tag: buy_1|
|Exit Reason: fastk_profit_sell|Exit Reason: fastk_profit_sell_2|
|Direction: Long|Direction: Long|
|Amount: 85.66|Amount: 85.32|
|Open Rate: 5.856 USDT|Open Rate: 5.853 USDT|
|Exit Rate: 5.902 USDT|Exit Rate: 5.903 USDT|
|Duration: 0:20:02 (20.0 min)|Duration: 0:19:32 (19.5 min)|
|||
|> Freqtrade Mastaaa:|> Fretrade_mastaaa_test:|
|✓ Binance (dry): New Trade filled (#4)|✓ Binance (dry): New Trade filled (#3)|
|Pair: VET/USDT|Pair: VET/USDT|
|Enter Tag: buy_1|Enter Tag: buy_1|
|Amount: 11287.5|Amount: 11248.3|
|Direction: Long|Direction: Long|
|Open Rate: 0.0446 USDT|Open Rate: 0.04455 USDT|
|Total: 503.423 USDT / 503.926 USD|Total: 501.112 USDT / 501.613 USD|
|||
|> Freqtrade Mastaaa:|> Fretrade_mastaaa_test:|
|✓ Binance (dry): New Trade filled (#5)|✓ Binance (dry): New Trade filled (#4)|
|Pair: TLM/USDT|Pair: TLM/USDT|
|Enter Tag: buy_1|Enter Tag: buy_1|
|Amount: 38719|Amount: 38500|
|Direction: Long|Direction: Long|
|Open Rate: 0.01299 USDT|Open Rate: 0.01301 USDT|
|Total: 502.96 USDT / 503.463 USD|Total: 500.885 USDT / 501.386 USD|
|||
|> Freqtrade Mastaaa:|> Fretrade_mastaaa_test:|
|✳ Binance (dry): Exited TLM/USDT (#5)|✳ Binance (dry): Exited TLM/USDT (#4)|
|Profit: 0.26% (profit: 1.315 USDT / 1.316 USD)|Profit: 0.26% (profit: 1.306 USDT / 1.307 USD)|
|Enter Tag: buy_1|Enter Tag: buy_1|
|Exit Reason: fastk_profit_sell|Exit Reason: fastk_profit_sell_2|
|Direction: Long|Direction: Long|
|Amount: 38719|Amount: 38500|
|Open Rate: 0.013 USDT|Open Rate: 0.013 USDT|
|Exit Rate: 0.013 USDT|Exit Rate: 0.013 USDT|
|Duration: 0:45:03 (45.0 min)|Duration: 0:44:31 (44.5 min)|
|||
|Day (count)     USDT         USD        Profit %|Day (count)     USDT         USD        Profit %|
|--------------  -----------  ---------  ----------|--------------  -----------  ---------  ----------|
|2024-11-23 (3)  14.505 USDT  14.52 USD  1.46%|2024-11-23 (3)  13.434 USDT  13.45 USD  1.36%

COTI exit was better on regular strat but TIA/USDT was better with you custom exit.
Will see on more trades :)

(Maybe let's continue this talk on discord ? To avoid spamming github comment's. My discord username : dadacticiel)

**Comment by Mastaaa1987** [comment]
Your message could not be delivered. This usually happens because you do not share a server with the recipient or the recipient only accepts direct messages from friends. You can see the full list of reasons here: https://support.discord.com/hc/en/articles/360060145013

**Comment by Mastaaa1987** [comment]
sorry for the chat attacke, i think you can close this issue ... :-)

**Comment by ssssi** [comment]
> sorry for the chat attacke, i think you can close this issue ... :-)

never mind.thanks for support.bro
