### ISSUE TITLE
我看电报机器人那个min profit, Max profit不错，这个没有进行PR吗？

### ISSUE THREAD

**Issue by 14790897** [ssssi/freqtrade_strs#26]
https://github.com/ssssi/freqtrade_strs/blob/main/binance/some_feature/max_min_profit%2Bcode/max_min.patch

支持一下，做得很好

**Comment by ssssi** [comment]
没有，freqtrade的作者应该知道这个功能的实现，但是一直没有加进去，应该有他的原因
