### ISSUE TITLE
Performance not same as your's

### ISSUE THREAD

**Issue by Smalltarget108** [ssssi/freqtrade_strs#3]
Hello,
Thank you for your very good strategy,
I have backtesting with the same config as you offered, but my result is bad (about 40% profit same data)than yours,
Is there some more tricks i need to pay attention on
Thank you

**Comment by ssssi** [comment]
> Hello, Thank you for your very good strategy, I have backtesting with the same config as you offered, but my result is bad (about 40% profit same data)than yours, Is there some more tricks i need to pay attention on Thank you

what str did you backtest?It is accurate relative to other exchanges in config_binance_future.json.

**Comment by Smalltarget108** [comment]
I use the str & config same as in the Repository

Str:
binance/BinHV27/short/BinHV27_short.py

config  binance/future_config/config_binance_future.json
            binance/BinHV27/short/TMP/BinHV27_short.json
the second config overwrites the first one.

the only difference is the "1000SHIB/USDT" & "1000XEC/USDT",
when I tried to download the data, it shows these two are not available.

 40%+ profit on   ( 2022-01-07 00:00:00  | | 2022-04-22 00:00:00  )
-2% profit latest month

**Comment by ssssi** [comment]
> I use the str & config same as in the Repository
> 
> Str: binance/BinHV27/short/BinHV27_short.py
> 
> config binance/future_config/config_binance_future.json binance/BinHV27/short/TMP/BinHV27_short.json the second config overwrites the first one.
> 
> the only difference is the "1000SHIB/USDT" & "1000XEC/USDT", when I tried to download the data, it shows these two are not available.
> 
> 40%+ profit on ( 2022-01-07 00:00:00 | | 2022-04-22 00:00:00 ) -2% profit latest month

the hypered file i still in testing，these days i am running a new hypered file.but 2022-01-07 00:00:00 | | 2022-04-22 00:00:00 backtest only 40% profit. that is impossible.

![image](https://user-images.githubusercontent.com/11401775/165061392-99f25e3a-f7b6-4952-9156-b320574678f0.png)

**Comment by Smalltarget108** [comment]
Hi,
Have you used the freqUI when running the short Str,
I only see the "long" & "long exit" on the top-right
![image](https://user-images.githubusercontent.com/52121280/165144496-6460ec7a-1a16-48e0-8392-a31b501dc37c.png)
Is It not compatible now
Thank you

**Comment by ssssi** [comment]
> Hi, Have you used the freqUI when running the short Str, I only see the "long" & "long exit" on the top-right
> 
> ![image](https://user-images.githubusercontent.com/52121280/165144496-6460ec7a-1a16-48e0-8392-a31b501dc37c.png)
> 
> Is It not compatible now Thank you

sorry.I'm not using freqUI yet.I currently only use Telegram .so i don't kown about this.i had plot a pair for BinHV27_short.i can send you,You can refer to it.

**Comment by ssssi** [comment]
[freqtrade-plot-BAND_USDT-5m.zip](https://github.com/ssssi/freqtrade_strs/files/8560712/freqtrade-plot-BAND_USDT-5m.zip)

**Comment by ketank1000** [comment]
@ssssi  Thanks for this strategy ! 
Im trying to backtesting you strategy but getting different results. I too used same config files which you have provided.

<img width="829" alt="Screenshot 2022-04-26 at 1 54 30 PM" src="https://user-images.githubusercontent.com/11884142/165256197-c5426e81-7f59-4508-85bb-bc17271229ab.png">

Also im backtesting your strategy in docker (develop) image.

**Comment by Smalltarget108** [comment]
> [freqtrade-plot-BAND_USDT-5m.zip](https://github.com/ssssi/freqtrade_strs/files/8560712/freqtrade-plot-BAND_USDT-5m.zip)

Ohhh...
This  plot looks really cool, 

I tried dry-run on BinHV27_short last night, but no deal happened,
In the backtesting result, it shows trade 7~9 times/ day.

I am wondering if  am using the same version freqtrade as you,
[https://github.com/freqtrade/freqtrade/tree/develop](https://github.com/freqtrade/freqtrade/tree/develop)

**Comment by ssssi** [comment]
> @ssssi Thanks for this strategy ! Im trying to backtesting you strategy but getting different results. I too used same config files which you have provided.
> 
> <img alt="Screenshot 2022-04-26 at 1 54 30 PM" width="829" src="https://user-images.githubusercontent.com/11884142/165256197-c5426e81-7f59-4508-85bb-bc17271229ab.png">
> 
> Also im backtesting your strategy in docker (develop) image.

sorry,I don't know why our backtest results are so different.it is so weird.
[BinHV27_short.zip](https://github.com/ssssi/freqtrade_strs/files/8561642/BinHV27_short.zip)
maybe you can try this.

![Snipaste_2022-04-26_17-17-13](https://user-images.githubusercontent.com/11401775/165266976-c7f1e2bd-56c9-404d-ad2b-935d79f7aa91.png)

**Comment by ssssi** [comment]
> > [freqtrade-plot-BAND_USDT-5m.zip](https://github.com/ssssi/freqtrade_strs/files/8560712/freqtrade-plot-BAND_USDT-5m.zip)
> 
> Ohhh... This plot looks really cool,
> 
> I tried dry-run on BinHV27_short last night, but no deal happened, In the backtesting result, it shows trade 7~9 times/ day.
> 
> I am wondering if i am using the same version freqtrade as you, https://github.com/freqtrade/freqtrade/tree/develop

yes.we same.i also use develop branch.do you use my hypered file?

**Comment by ssssi** [comment]
> > [freqtrade-plot-BAND_USDT-5m.zip](https://github.com/ssssi/freqtrade_strs/files/8560712/freqtrade-plot-BAND_USDT-5m.zip)
> 
> Ohhh... This plot looks really cool,
> 
> I tried dry-run on BinHV27_short last night, but no deal happened, In the backtesting result, it shows trade 7~9 times/ day.
> 
> I am wondering if i am using the same version freqtrade as you, https://github.com/freqtrade/freqtrade/tree/develop

why it is so slient in today,becaus

**Comment by ssssi** [comment]
@ketank1000 @Smalltarget108 I accidentally closed this issue. If there is any problem, you can reopen an issue

**Comment by ketank1000** [comment]
@ssssi Thanks !
All working fine. I debugged and found config file wasn't overriding the parameters.
