### ISSUE TITLE
Can we open short positions live ?

### ISSUE THREAD

**Issue by ketank1000** [ssssi/freqtrade_strs#4]
As per docs Freqtrade does not support trading with margin / leverage, and cannot open short positions.
https://www.freqtrade.io/en/stable/faq/#can-i-open-short-positions

How are you planing run this str live ?

**Comment by ssssi** [comment]
> As per docs Freqtrade does not support trading with margin / leverage, and cannot open short positions. https://www.freqtrade.io/en/stable/faq/#can-i-open-short-positions
> 
> How are you planing run this str live ?

the develop branch can support future.
✳ Binance: Exiting MANA/USDT (#7)
Unrealized Profit: 2.08% (profit: 6.47085816 USDT / 42.384 CNY)
Enter Tag: buy_2
Exit Reason: trailing_stop_loss
Duration: 0:26:49 (26.8 min)
Direction: Short
Leverage: 5.0
Amount: 806.00000000
Open Rate: 1.93350000
Current Rate: 1.92470000
Close Rate: 1.92470000

**Comment by ketank1000** [comment]
Can you help me on this ?

`Traceback (most recent call last):
futures_long        |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
futures_long        |     worker = Worker(args)
futures_long        |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
futures_long        |     self._init(False)
futures_long        |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
futures_long        |     self.freqtrade = FreqtradeBot(self._config)
futures_long        |   File "/freqtrade/freqtrade/freqtradebot.py", line 67, in __init__
futures_long        |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
futures_long        |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
futures_long        |     exchange = ExchangeResolver._load_exchange(exchange_name,
futures_long        |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
futures_long        |     exchange = ex_class(**kwargs)
futures_long        |   File "/freqtrade/freqtrade/exchange/exchange.py", line 196, in __init__
futures_long        |     self.fill_leverage_tiers()
futures_long        |   File "/freqtrade/freqtrade/exchange/exchange.py", line 2136, in fill_leverage_tiers
futures_long        |     leverage_tiers = self.load_leverage_tiers()
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 154, in wrapper
futures_long        |     return wrapper(*args, **kwargs)
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 154, in wrapper
futures_long        |     return wrapper(*args, **kwargs)
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 154, in wrapper
futures_long        |     return wrapper(*args, **kwargs)
futures_long        |   [Previous line repeated 1 more time]
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 157, in wrapper
futures_long        |     raise ex
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 142, in wrapper
futures_long        |     return f(*args, **kwargs)
futures_long        |   File "/freqtrade/freqtrade/exchange/binance.py", line 202, in load_leverage_tiers
futures_long        |     raise TemporaryError(f'Could not fetch leverage amounts due to'
futures_long        | freqtrade.exceptions.TemporaryError: Could not fetch leverage amounts due toAuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: XX.XX.XX.XX"}`

My api key is failing for this.
