### ISSUE TITLE
How to use strategy config

### ISSUE THREAD

**Issue by Smalltarget108** [ssssi/freqtrade_strs#5]
Hello, 

When I try to use your strategy config by multi  config command:
freqtrade trade  -s stra.py --config user_data/config.json --config user_data/BinHV27_short.json 

it shows that the second config does not overwrite the corresponding value in the stra.py
Am I using it in the wrong manner?

Thanks a lot!

**Comment by ssssi** [comment]
> Hello,
> 
> When I try to use your strategy config by multi config command: freqtrade trade -s stra.py --config user_data/config.json --config user_data/BinHV27_short.json
> 
> it shows that the second config does not overwrite the corresponding value in the stra.py Am I using it in the wrong manner?
> 
> Thanks a lot!

freqtrade trade -s stra.py --config user_data/config.json
try this.

**Comment by Smalltarget108** [comment]
> > Hello,
> > When I try to use your strategy config by multi config command: freqtrade trade -s stra.py --config user_data/config.json --config user_data/BinHV27_short.json
> > it shows that the second config does not overwrite the corresponding value in the stra.py Am I using it in the wrong manner?
> > Thanks a lot!
> 
> freqtrade trade -s stra.py --config user_data/config.json try this.
Thank you
