### ISSUE TITLE
Config for ConsensusShort.py?

### ISSUE THREAD

**Issue by ChronoBrake** [ssssi/freqtrade_strs#6]
Hey anyone have config for this?
https://github.com/ssssi/freqtrade_strs/blob/main/binance/ConsensusShort/ConsensusShort.py
Regards

**Comment by ssssi** [comment]
> Hey anyone have config for this? https://github.com/ssssi/freqtrade_strs/blob/main/binance/ConsensusShort/ConsensusShort.py Regards

you can use my HO files.my dry run now is ConsensusShort.json_roi_x3.but you need rename it to ConsensusShort.json
and config.json you can use :https://github.com/ssssi/freqtrade_strs/blob/main/binance/future_config/config_binance_future.json

but you need dry run first to see whether it can use for live.

**Comment by ChronoBrake** [comment]
Hey, i download and setup config.json. Strategy running fine, but i don't know what to do with ConsensusShort.json_roi_x3. Only rename it to json file? Stupid question, but how i can push that second json to strategy? I must add something to starting command line or manually edit strategy file? It's be something like --config x.sjon?
Regards

**Comment by ssssi** [comment]
> Hey, i download and setup config.json. Strategy running fine, but i don't know what to do with ConsensusShort.json_roi_x3. Only rename it to json file? Stupid question, but how i can push that second json to strategy? I must add something to starting command line or manually edit strategy file? It's be something like --config x.sjon?
> 
> And second question. I want to test dynamic pairlist. That volume pairlist be good in your dry run or you disabled it bcs low result?
> 
> ```
>   "pairlists": [
> //        {
> //            "method": "VolumePairList",
> //            "number_assets": 150,
> //            "sort_key": "quoteVolume",
> //            "refresh_period": 1800
> //        },
> //        {"method": "AgeFilter", "min_days_listed": 7},
> //        {
> //            "method": "VolatilityFilter",
> //            "lookback_days": 3,
> //            "min_volatility": 0.02,
> //            "max_volatility": 0.75,
> //            "refresh_period": 1800
> //        },
> //        {
> //        "method": "RangeStabilityFilter",
> //        "lookback_days": 3,
> //        "min_rate_of_change": 0.05,
> //        "refresh_period": 1800
> //        },
> //        {
> //        "method": "PerformanceFilter"
> //        }
>      {
>       "method": "StaticPairList"
>     },
>     {"method": "ShuffleFilter", "seed": 42}
>     ],
> ```
> 
> Also add to repo btc addr for tips, i wanan use it :D Regards

yes,if you want use HO file, Only rename it to .json file.
