### ISSUE TITLE
How you tune the stra parameters

### ISSUE THREAD

**Issue by Smalltarget108** [ssssi/freqtrade_strs#7]
Hello,

Good day.
I am confused about the Stra parameters tuning ,
I have tried the freqtrade 'hyperopt', but can only use one month data for it on my 64G CPU-memory PC,
It turns out that it can fit the used data, but get really bad performance on the non-seen data.
How you do the parameter fine-turning

Thank you.

**Comment by ssssi** [comment]
> Hello,
> 
> Good day. I am confused about the Stra parameters tuning , I have tried the freqtrade 'hyperopt', but can only use one month data for it on my 64G CPU-memory PC, It turns out that it can fit the used data, but get really bad performance on the non-seen data. How you do the parameter fine-turning
> 
> Thank you.

i don't kown you mean,did you mean how to HO params?

**Comment by abbaselmas** [comment]
You most probably have lots of pairs in your pairlist. Reduce your pairlist so that you can use more than one month data for that pairlist.

**Comment by ssssi** [comment]
> > Hello,
> > Good day. I am confused about the Stra parameters tuning , I have tried the freqtrade 'hyperopt', but can only use one month data for it on my 64G CPU-memory PC, It turns out that it can fit the used data, but get really bad performance on the non-seen data. How you do the parameter fine-turning
> > Thank you.
> 
> i don't kown you mean,did you mean how to HO params?

if you have any question you can connect with me in discard.i will close this issue
