### ISSUE TITLE
Is there any ability to short in BBMod strats

### ISSUE THREAD

**Issue by peterphan1996** [ssssi/freqtrade_strs#9]
Hello,

As mentioned in the title, how can we add short signal in BBMod strategy?

**Comment by ssssi** [comment]
> Hello,
> 
> As mentioned in the title, how can we add short signal in BBMod strategy

yes,you can.you can write like this:

dataframe.loc[(), ['enter_short', 'enter_tag']] = (1, 'long_in')

**Comment by peterphan1996** [comment]
oh sorry, I mean what is the correct condition to add for short? Like for BBMod, we have a bunch of conditions for long, how about for short

**Comment by ssssi** [comment]
> oh sorry, I mean what is the correct condition to add for short? Like for BBMod, we have a bunch of conditions for long, how about for short

i still can not find good short signal.in current market, i think long is work better than short.

**Comment by ssssi** [comment]
if you have any question.you can open another issue.
